### ISSUE TITLE
is json module allowed to have BOM?

### ISSUE THREAD

**Issue by aladdin-add** [tc39/proposal-json-modules#21]
I guess it's fine to have/have not. so, which is preferred? :)

**Comment by Andrew-Cottrell** [comment]
https://www.rfc-editor.org/rfc/rfc7159#section-8.1

> **The JavaScript Object Notation (JSON) Data Interchange Format** (RFC 7159, March 2014)
> **8.  String and Character Issues**
> **8.1.  Character Encoding**
> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.
